### ISSUE TITLE
nsatisfiedLinkError

### ISSUE THREAD

**Issue by ZhangKuixun** [joaoventura/pybridge#24]
java.lang.UnsatisfiedLinkError: No implementation found for int demo.chaquopy.pythonactivity.jniPython.Util.run(java.lang.String) (tried Java_demo_chaquopy_pythonactivity_jniPython_Util_run and Java_demo_chaquopy_pythonactivity_jniPython_Util_run__Ljava_lang_String_2)

E/zygote64: No implementation found for int demo.chaquopy.pythonactivity.jniPython.Util.run(java.lang.String) (tried Java_demo_chaquopy_pythonactivity_jniPython_Util_run and Java_demo_chaquopy_pythonactivity_jniPython_Util_run__Ljava_lang_String_2)
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask `#1`
    Process: demo.chaquopy.pythonactivity, PID: 6671
    java.lang.UnsatisfiedLinkError: No implementation found for int demo.chaquopy.pythonactivity.jniPython.Util.run(java.lang.String) (tried Java_demo_chaquopy_pythonactivity_jniPython_Util_run and Java_demo_chaquopy_pythonactivity_jniPython_Util_run__Ljava_lang_String_2)
        at demo.chaquopy.pythonactivity.jniPython.Util.run(Native Method)
        at demo.chaquopy.pythonactivity.jniPython.MainActivity$1.run(MainActivity.java:27)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by ZhangKuixun** [comment]
already solve

**Comment by joaoventura** [comment]
Issues are not meant to be used for user support, please don't do this here! 👎
