### ISSUE TITLE
Followed all the mention steps But I get  "libpybridge.so" not found

### ISSUE THREAD

**Issue by AmitGupta1994** [joaoventura/pybridge#35]
java.lang.UnsatisfiedLinkError: dlopen failed: library "libpybridge.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        **at com.jventura.pybridge.PyBridge.<clinit>(PyBridge.java:50)**
        at com.jventura.pybridge.PyBridge.start(Native Method)
        **at com.jventura.pyapp.MainActivity.onCreate(MainActivity.java:34)**

**Comment by zedelaaaa** [comment]
can you share libpybridge.so file?
